// fields.glsl — the force-field library. Prepended to the simulation shaders
// (after common.glsl, whose hash13() this uses).
//
// Every field here is a real mechanism, not a decorative wiggle:
//
//   windForce      curl of a stream function -> DIVERGENCE-FREE flow. No sources
//                  or sinks, so dust folds and swirls like air instead of being
//                  pumped into blobs. This is what makes "carried away in the
//                  wind" read as wind.
//
//   poleField      two opposite magnetic poles. Iron filings do two things at
//                  once: they ADVECT along B and they ALIGN to B. We advect
//                  here; the splat shader aligns its billboard to velocity,
//                  which (when this field dominates) IS the field direction.
//
//   chladniForce   sand on a vibrating plate collects at the NODES of the
//                  standing wave, where displacement is zero. We descend
//                  grad(u^2), which is exactly "move away from vibration".
//
//   moireForce     two Penrose-class quasilattices, one rotating over the other.
//                  A 5-fold quasicrystal is generated by five plane waves at
//                  72 degrees (that is its Fourier signature). Superposing two
//                  of them at a slow relative rotation produces structure at a
//                  scale far larger than either lattice, reorganising forever.
//
//   gravityForce   softened inverse-square from moving bodies. Three bodies is
//                  the canonical chaotic system: bounded, deterministic, never
//                  repeating.

const float TAU5 = 1.25663706;   // 2*pi/5, the Penrose angle
const float PI_  = 3.14159265;

// ---- cheap value noise, 3 octaves (fields only; common.glsl's fbm is 5) ----
float fnoise2(vec2 p) {
  vec2 i = floor(p), f = fract(p);
  f = f * f * (3.0 - 2.0 * f);
  float a = hash13(vec3(i, 0.0));
  float b = hash13(vec3(i + vec2(1.0, 0.0), 0.0));
  float c = hash13(vec3(i + vec2(0.0, 1.0), 0.0));
  float d = hash13(vec3(i + vec2(1.0, 1.0), 0.0));
  return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float ffbm(vec2 p) {
  float v = 0.0, a = 0.5;
  mat2 r = mat2(0.8, -0.6, 0.6, 0.8);
  for (int i = 0; i < 3; i++) { v += a * fnoise2(p); p = r * p * 2.0; a *= 0.5; }
  return v;
}

// ---- wind: 2.5D curl noise ------------------------------------------------
// The horizontal component is the curl of a scalar stream function, so it is
// exactly divergence-free in the xz plane (incompressible, no accumulation
// artefacts). Vertical lift comes from an independent noise so dust can rise.
vec3 windForce(vec3 p, float t, float scale) {
  vec2 q = p.xz * scale + vec2(t * 0.05, -t * 0.04);
  float e = 0.15;
  float dpx = ffbm(q + vec2(e, 0.0)) - ffbm(q - vec2(e, 0.0));
  float dpz = ffbm(q + vec2(0.0, e)) - ffbm(q - vec2(0.0, e));
  vec2 h = vec2(dpz, -dpx) / (2.0 * e);          // curl -> divergence-free
  float lift = ffbm(q * 1.7 + vec2(7.3, -2.1)) - 0.5;
  return vec3(h.x, lift * 0.6, h.y);
}

// ---- magnetism: field of two opposite poles (a bar magnet) ----------------
// Field lines run from the + pole to the - pole. Advecting along this is what
// gathers dust into the classic looping filing arcs.
vec3 poleField(vec3 p, vec3 pPos, vec3 pNeg) {
  vec3 a = p - pPos; float da = dot(a, a) + 0.03;
  vec3 b = p - pNeg; float db = dot(b, b) + 0.03;
  return a / (da * sqrt(da)) - b / (db * sqrt(db));
}

// ---- Chladni: sand collects on the nodal lines -----------------------------
// u(x,z) = cos(n pi x)cos(m pi z) - cos(m pi x)cos(n pi z)   (square plate)
// Sand is shaken off the antinodes and settles where |u| -> 0, so we descend
// grad(u^2) = 2u grad(u). Changing (n,m) makes the sand re-collect into a
// completely different figure — memories reforming as a new shape.
vec3 chladniForce(vec3 p, vec2 nm, float invExtent) {
  vec2 q = p.xz * invExtent;
  float n = nm.x, m = nm.y;
  float cnx = cos(n * PI_ * q.x), cmx = cos(m * PI_ * q.x);
  float cnz = cos(n * PI_ * q.y), cmz = cos(m * PI_ * q.y);
  float snx = sin(n * PI_ * q.x), smx = sin(m * PI_ * q.x);
  float snz = sin(n * PI_ * q.y), smz = sin(m * PI_ * q.y);
  float u    = cnx * cmz - cmx * cnz;
  float dudx = (-n * PI_ * snx * cmz) + (m * PI_ * smx * cnz);
  float dudz = (-m * PI_ * cnx * smz) + (n * PI_ * cmx * snz);
  vec2 g = -2.0 * u * vec2(dudx, dudz) * invExtent;
  return vec3(g.x, 0.0, g.y) * 0.12;
}

// ---- Penrose quasilattice: five plane waves at 72 degrees ------------------
// Returns the scalar field and (via `grad`) its analytic gradient, so the
// interference force below costs no finite differences.
float quasi(vec2 q, float rot, float freq, out vec2 grad) {
  float s = 0.0;
  grad = vec2(0.0);
  for (int k = 0; k < 5; k++) {
    float a = rot + float(k) * TAU5;
    vec2 kv = vec2(cos(a), sin(a)) * freq;
    float ph = dot(kv, q);
    s += cos(ph);
    grad += -sin(ph) * kv;
  }
  return s;
}

// ---- moire: two quasilattices, one rotating over the other -----------------
// The product A*B is the interference term. Descending its gradient collects
// dust into the beat pattern — which is vastly larger-scale than either
// lattice and never repeats as the relative rotation advances.
vec3 moireForce(vec3 p, float rotA, float rotB, float freq, float invExtent) {
  vec2 q = p.xz * invExtent;
  vec2 gA, gB;
  float A = quasi(q, rotA, freq, gA);
  float B = quasi(q, rotB, freq, gB);
  vec2 g = (A * gB + B * gA) * invExtent;
  return vec3(-g.x, 0.0, -g.y) * 0.045;
}

// ---- gravity: softened inverse-square from moving bodies -------------------
// xyz = position, w = mass. Softening keeps the singularity from exploding the
// integrator when a splat passes through a body.
vec3 gravityForce(vec3 p, vec4 b0, vec4 b1, vec4 b2) {
  vec3 f = vec3(0.0), r;
  float d2;
  r = b0.xyz - p; d2 = dot(r, r) + 0.08; f += b0.w * r / (d2 * sqrt(d2));
  r = b1.xyz - p; d2 = dot(r, r) + 0.08; f += b1.w * r / (d2 * sqrt(d2));
  r = b2.xyz - p; d2 = dot(r, r) + 0.08; f += b2.w * r / (d2 * sqrt(d2));
  return f;
}

// ---- hands: radial push / pull with a soft gaussian falloff ---------------
// w > 0 repels (blow the dust away), w < 0 attracts (gather it in).
vec3 handForce(vec3 p, vec4 h) {
  vec3 r = p - h.xyz;
  float d2 = dot(r, r) + 0.008;
  float fall = exp(-d2 * 5.0);
  return r * inversesqrt(d2) * h.w * fall;
}
